### ISSUE TITLE
敲碗敲碗~

### ISSUE THREAD

**Issue by wudijimao** [su350380433/iOS_build_share_article#1]
https://github.com/YoudaoMobile/cocoapods-dev-env
我们有个开源的，用于便捷切换submodule/tag/release开发的，贵项目开源的话考虑结合起来联动一下

**Comment by su350380433** [comment]
感谢

**Comment by su350380433** [comment]
我们的项目开源了，您也可以给我们提PR
https://github.com/MeetYouDevs/cocoapods-imy-bin
